# Submission Evaluation - Stage 2

In [1]:
import os

# Move up one level to set the working directory to the repo root
os.chdir(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [1]:
import os

os.getcwd()

'C:\\Users\\brown\\Documents\\GitHub\\march-machine-learning-mania'

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

KAGGLE_DATA_PATH = Path(os.path.abspath(os.path.join(os.getcwd(), r"data\kaggle")))
SUBMISSION_DATA_PATH = Path(
    os.path.abspath(os.path.join(os.getcwd(), r"data\submissions"))
)
DATA_PATH = Path(os.path.abspath(os.path.join(os.getcwd(), r"data")))

In [19]:
# Load data
submission_df = pd.read_csv(KAGGLE_DATA_PATH / "SampleSubmissionStage2.csv")
m_seeds = pd.read_csv(KAGGLE_DATA_PATH / "MNCAATourneySeeds.csv")
w_seeds = pd.read_csv(KAGGLE_DATA_PATH / "WNCAATourneySeeds.csv")
m_teams = pd.read_csv(KAGGLE_DATA_PATH / "MTeams.csv")
w_teams = pd.read_csv(KAGGLE_DATA_PATH / "WTeams.csv")
tourney_rounds = pd.read_csv(DATA_PATH / "tourney_round_lookup.csv")

# Extract Season, Team1, and Team2 from ID
submission_df[["Season", "Team1", "Team2"]] = submission_df["ID"].str.split(
    "_", expand=True
)
submission_df[["Season", "Team1", "Team2"]] = submission_df[
    ["Season", "Team1", "Team2"]
].astype(int)

# Get Gender
submission_df["Gender"] = np.where(submission_df["Team1"] >= 3000, "Women", "Men")

# Merge Team Name
mw_teams = pd.concat([m_teams, w_teams], ignore_index=True)
submission_df = submission_df.merge(
    mw_teams[["TeamID", "TeamName"]], left_on=["Team1"], right_on=["TeamID"], how="left"
).rename(columns={"TeamName": "TeamName1"})
submission_df = submission_df.merge(
    mw_teams[["TeamID", "TeamName"]], left_on=["Team2"], right_on=["TeamID"], how="left"
).rename(columns={"TeamName": "TeamName2"})
submission_df.drop(columns=["TeamID_x", "TeamID_y"], inplace=True)


# Function to get seed values
def get_seed_values(seed):
    return int(seed[1:3])


m_seeds["SeedValue"] = m_seeds["Seed"].apply(get_seed_values)
w_seeds["SeedValue"] = w_seeds["Seed"].apply(get_seed_values)

mw_seeds = pd.concat([m_seeds, w_seeds], ignore_index=True)


# Merge Seeds
submission_df = submission_df.merge(
    mw_seeds, left_on=["Season", "Team1"], right_on=["Season", "TeamID"], how="left"
).rename(columns={"Seed": "Seed1", "SeedValue": "SeedValue1"})
submission_df = submission_df.merge(
    mw_seeds, left_on=["Season", "Team2"], right_on=["Season", "TeamID"], how="left"
).rename(columns={"Seed": "Seed2", "SeedValue": "SeedValue2"})
submission_df.drop(columns=["TeamID_x", "TeamID_y"], inplace=True)


# Ensure Seed1 and Seed2 are strings
submission_df["Seed1"] = submission_df["Seed1"].astype(str)
submission_df["Seed2"] = submission_df["Seed2"].astype(str)

# Create StrongSeed and WeakSeed
submission_df["StrongSeed"] = submission_df[["Seed1", "Seed2"]].min(axis=1)
submission_df["WeakSeed"] = submission_df[["Seed1", "Seed2"]].max(axis=1)


# Function to clean seed values
def clean_seed(seed):
    return seed[:-1] if seed[-1] in ["a", "b"] else seed


submission_df["StrongSeed"] = submission_df["StrongSeed"].apply(clean_seed)
submission_df["WeakSeed"] = submission_df["WeakSeed"].apply(clean_seed)

submission_df["StrongSeedValue"] = submission_df[["SeedValue1", "SeedValue2"]].min(
    axis=1
)
submission_df["WeakSeedValue"] = submission_df[["SeedValue1", "SeedValue2"]].max(axis=1)


# Merge Round Info
submission_df = submission_df.merge(
    tourney_rounds,
    left_on=["StrongSeed", "WeakSeed"],
    right_on=["StrongSeed", "WeakSeed"],
    how="left",
)

In [20]:
submission_df

,ID,Pred,Season,Team1,Team2,Gender,TeamName1,TeamName2,Seed1,SeedValue1,Seed2,SeedValue2,StrongSeed,WeakSeed,StrongSeedValue,WeakSeedValue,Round,Slot
0,2025_1101_1102,0.5,2025,1101,1102,Men,Abilene Chr,Air Force,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
1,2025_1101_1103,0.5,2025,1101,1103,Men,Abilene Chr,Akron,nan,NaN,W13,13.0,W13,nan,13.0,13.0,NaN,NaN
2,2025_1101_1104,0.5,2025,1101,1104,Men,Abilene Chr,Alabama,nan,NaN,W02,2.0,W02,nan,2.0,2.0,NaN,NaN
3,2025_1101_1105,0.5,2025,1101,1105,Men,Abilene Chr,Alabama A&M,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
4,2025_1101_1106,0.5,2025,1101,1106,Men,Abilene Chr,Alabama St,nan,NaN,Y16a,16.0,Y16,nan,16.0,16.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131402,2025_3477_3479,0.5,2025,3477,3479,Women,East Texas A&M,Mercyhurst,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
131403,2025_3477_3480,0.5,2025,3477,3480,Women,East Texas A&M,West Georgia,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
131404,2025_3478_3479,0.5,2025,3478,3479,Women,Le Moyne,Mercyhurst,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
131405,2025_3478_3480,0.5,2025,3478,3480,Women,Le Moyne,West Georgia,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN
131406,2025_3479_3480,0.5,2025,3479,3480,Women,Mercyhurst,West Georgia,nan,NaN,nan,NaN,nan,nan,NaN,NaN,NaN,NaN

In [21]:
submission_df[(submission_df["Gender"] == "Men") & (submission_df["Round"] == 1)]

,ID,Pred,Season,Team1,Team2,Gender,TeamName1,TeamName2,Seed1,SeedValue1,Seed2,SeedValue2,StrongSeed,WeakSeed,StrongSeedValue,WeakSeedValue,Round,Slot
732,2025_1103_1112,0.5,2025,1103,1112,Men,Akron,Arizona,W13,13.0,W04,4.0,W04,W13,4.0,13.0,1.0,R1W4
1322,2025_1104_1352,0.5,2025,1104,1352,Men,Alabama,Robert Morris,W02,2.0,W15,15.0,W02,W15,2.0,15.0,1.0,R1W2
1816,2025_1106_1120,0.5,2025,1106,1120,Men,Alabama St,Auburn,Y16a,16.0,Y01,1.0,Y01,Y16,1.0,16.0,1.0,R1Y1
2941,2025_1110_1181,0.5,2025,1110,1181,Men,American Univ,Duke,W16a,16.0,W01,1.0,W01,W16,1.0,16.0,1.0,R1W1
5109,2025_1116_1242,0.5,2025,1116,1242,Men,Arkansas,Kansas,Z10,10.0,Z07,7.0,Z07,Z10,7.0,10.0,1.0,R1Z7
6287,2025_1120_1384,0.5,2025,1120,1384,Men,Auburn,St Francis PA,Y01,1.0,Y16b,16.0,Y01,Y16,1.0,16.0,1.0,R1Y1
7220,2025_1124_1280,0.5,2025,1124,1280,Men,Baylor,Mississippi St,W09,9.0,W08,8.0,W08,W09,8.0,9.0,1.0,R1W8
10592,2025_1136_1277,0.5,2025,1136,1277,Men,Bryant,Michigan St,Y15,15.0,Y02,2.0,Y02,Y15,2.0,15.0,1.0,R1Y2
12064,2025_1140_1433,0.5,2025,1140,1433,Men,BYU,VCU,W06,6.0,W11,11.0,W06,W11,6.0,11.0,1.0,R1W6
16408,2025_1155_1270,0.5,2025,1155,1270,Men,Clemson,McNeese St,X05,5.0,X12,12.0,X05,X12,5.0,12.0,1.0,R1X5
18279,2025_1161_1272,0.5,2025,1161,1272,Men,Colorado St,Memphis,Z12,12.0,Z05,5.0,Z05,Z12,5.0,12.0,1.0,R1Z5
18947,2025_1163_1328,0.5,2025,1163,1328,Men,Connecticut,Oklahoma,Z08,8.0,Z09,9.0,Z08,Z09,8.0,9.0,1.0,R1Z8
19794,2025_1166_1257,0.5,2025,1166,1257,Men,Creighton,Louisville,Y09,9.0,Y08,8.0,Y08,Y09,8.0,9.0,1.0,R1Y8
23679,2025_1179_1281,0.5,2025,1179,1281,Men,Drake,Missouri,Z11,11.0,Z06,6.0,Z06,Z11,6.0,11.0,1.0,R1Z6
24267,2025_1181_1291,0.5,2025,1181,1291,Men,Duke,Mt St Mary's,W01,1.0,W16b,16.0,W01,W16,1.0,16.0,1.0,R1W1
26194,2025_1188_1222,0.5,2025,1188,1222,Men,SIUE,Houston,X16,16.0,X01,1.0,X01,X16,1.0,16.0,1.0,R1X1
28503,2025_1196_1313,0.5,2025,1196,1313,Men,Florida,Norfolk St,Z01,1.0,Z16,16.0,Z01,Z16,1.0,16.0,1.0,R1Z1
31615,2025_1208_1211,0.5,2025,1208,1211,Men,Georgia,Gonzaga,X09,9.0,X08,8.0,X08,X09,8.0,9.0,1.0,R1X8
32965,2025_1213_1268,0.5,2025,1213,1268,Men,Grand Canyon,Maryland,Z13,13.0,Z04,4.0,Z04,Z13,4.0,13.0,1.0,R1Z4
34057,2025_1219_1345,0.5,2025,1219,1345,Men,High Point,Purdue,X13,13.0,X04,4.0,X04,X13,4.0,13.0,1.0,R1X4
36342,2025_1228_1400,0.5,2025,1228,1400,Men,Illinois,Texas,X06,6.0,X11a,11.0,X06,X11,6.0,11.0,1.0,R1X6
36401,2025_1228_1462,0.5,2025,1228,1462,Men,Illinois,Xavier,X06,6.0,X11b,11.0,X06,X11,6.0,11.0,1.0,R1X6
37879,2025_1235_1252,0.5,2025,1235,1252,Men,Iowa St,Lipscomb,Y03,3.0,Y14,14.0,Y03,Y14,3.0,14.0,1.0,R1Y3
40570,2025_1246_1407,0.5,2025,1246,1407,Men,Kentucky,Troy,X03,3.0,X14,14.0,X03,X14,3.0,14.0,1.0,R1X3
41612,2025_1251_1332,0.5,2025,1251,1332,Men,Liberty,Oregon,W12,12.0,W05,5.0,W05,W12,5.0,12.0,1.0,R1W5
44783,2025_1266_1307,0.5,2025,1266,1307,Men,Marquette,New Mexico,Y07,7.0,Y10,10.0,Y07,Y10,7.0,10.0,1.0,R1Y7
46946,2025_1276_1471,0.5,2025,1276,1471,Men,Michigan,UC San Diego,Y05,5.0,Y12,12.0,Y05,Y12,5.0,12.0,1.0,R1Y5
47377,2025_1279_1314,0.5,2025,1279,1314,Men,Mississippi,North Carolina,Y06,6.0,Y11a,11.0,Y06,Y11,6.0,11.0,1.0,R1Y6
47423,2025_1279_1361,0.5,2025,1279,1361,Men,Mississippi,San Diego St,Y06,6.0,Y11b,11.0,Y06,Y11,6.0,11.0,1.0,R1Y6
48652,2025_1285_1458,0.5,2025,1285,1458,Men,Montana,Wisconsin,W14,14.0,W03,3.0,W03,W14,3.0,14.0,1.0,R1W3
51438,2025_1303_1385,0.5,2025,1303,1385,Men,NE Omaha,St John's,Z15,15.0,Z02,2.0,Z02,Z15,2.0,15.0,1.0,R1Z2
62106,2025_1388_1435,0.5,2025,1388,1435,Men,St Mary's CA,Vanderbilt,W07,7.0,W10,10.0,W07,W10,7.0,10.0,1.0,R1W7
62884,2025_1397_1459,0.5,2025,1397,1459,Men,Tennessee,Wofford,X02,2.0,X15,15.0,X02,X15,2.0,15.0,1.0,R1X2
63198,2025_1401_1463,0.5,2025,1401,1463,Men,Texas A&M,Yale,Y04,4.0,Y13,13.0,Y04,Y13,4.0,13.0,1.0,R1Y4
63310,2025_1403_1423,0.5,2025,1403,1423,Men,Texas Tech,UNC Wilmington,Z03,3.0,Z14,14.0,Z03,Z14,3.0,14.0,1.0,R1Z3
64247,2025_1417_1429,0.5,2025,1417,1429,Men,UCLA,Utah St,X07,7.0,X10,10.0,X07,X10,7.0,10.0,1.0,R1X7

In [22]:
true_results_df = submission_df[submission_df["Round"] >= 1].copy()

In [24]:
true_results_df[
    [
        "ID",
        "Gender",
        "Seed1",
        "Team1",
        "TeamName1",
        "Seed2",
        "Team2",
        "TeamName2",
        "Round",
        "Slot",
    ]
].to_csv(DATA_PATH / "true_results_df.csv", index=False)